sudo: required
dist: trusty

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CC=gcc-6 CXX=g++-6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - g++-6
            - clang-3.8
      env: CC=clang-3.8 CXX=clang++-3.8
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: osx
      osx_image: xcode6.4
      compiler: clang
    - os: osx
      osx_image: beta-xcode6.1
      compiler: clang
