build:

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan # It install conan too
  - conan install --build=missing

build_script:
  - mkdir build && cd build
  - cmake -G "%TOOLCHAIN_VERSION%" ..
  - cmake --build . --config release

test_script:
- cmd: ctest -C release -VV

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.8"
  PYTHON_ARCH: "32"
  matrix:
    - TOOLCHAIN_VERSION: Visual Studio 14 2015 Win64
    - TOOLCHAIN_VERSION: Visual Studio 12 2013 Win64
    - TOOLCHAIN_VERSION: Visual Studio 11 2012 Win64
