build:

build_script:
  - mkdir build && cd build
  - if "%platform%"=="Win32" set CMAKE_GENERATOR="%TOOLCHAIN_VERSION%" ..
  - if "%platform%"=="x64" set CMAKE_GENERATOR="%TOOLCHAIN_VERSION% Win64" ..
  - cmake -G "%CMAKE_GENERATOR%" ..
  - cmake --build . --config release

test_script:
- cmd: ctest -C release -VV
platform:
  - Win32
  - x64
environment:
  matrix:
    - TOOLCHAIN_VERSION: Visual Studio 14 2015
    - TOOLCHAIN_VERSION: Visual Studio 12 2013
    - TOOLCHAIN_VERSION: Visual Studio 11 2012
